## Linear Algebra Advanced

**Resources: [Linear algebra (scipy.linalg)](https://docs.scipy.org/doc/scipy/reference/linalg.html#module-scipy.linalg)**

Note : ```scipy.linalg``` contains all the functions in ```numpy.linalg```. plus some other more advanced ones not contained in ```numpy.linalg```.

Another advantage of using ```scipy.linalg``` over ```numpy.linalg``` is that it is always compiled with BLAS/LAPACK support, while for numpy this is optional. Therefore, the scipy version might be faster depending on how numpy was installed.

Therefore, unless you don’t want to add scipy as a dependency to your numpy program, use ```scipy.linalg``` instead of ```numpy.linalg```.

In [17]:
import numpy as np
import scipy.linalg as LA
np.set_printoptions(precision=2, suppress=True)

### Matrix Functions

In [18]:
A = np.random.rand(3,3)
LA.expm(A)

array([[1.25, 1.04, 1.89],
       [0.83, 2.6 , 2.25],
       [0.38, 1.25, 2.99]])

In [19]:
LA.logm(A)

array([[-3.54, -0.17,  3.74],
       [ 3.22, -0.52, -1.57],
       [-1.09,  0.68,  0.55]])

In [20]:
LA.sinm(A)

array([[-0.06,  0.22,  0.64],
       [ 0.37,  0.42,  0.41],
       [ 0.02,  0.32,  0.57]])

### Singular Value Decomposition

#### 1. LU decomposition

#### 2. Cholesky decomposition

#### 3. QR decomposition

#### 4. Schur decomposition

### Special Matrices

- Hilbert Matrix

In [7]:
from scipy.linalg import hilbert
hilbert(5)

array([[1.  , 0.5 , 0.33, 0.25, 0.2 ],
       [0.5 , 0.33, 0.25, 0.2 , 0.17],
       [0.33, 0.25, 0.2 , 0.17, 0.14],
       [0.25, 0.2 , 0.17, 0.14, 0.12],
       [0.2 , 0.17, 0.14, 0.12, 0.11]])

- DFT matrix

In [8]:
from scipy.linalg import dft
m = dft(5)
print(m)

[[ 1.  +0.j    1.  +0.j    1.  +0.j    1.  +0.j    1.  +0.j  ]
 [ 1.  +0.j    0.31-0.95j -0.81-0.59j -0.81+0.59j  0.31+0.95j]
 [ 1.  +0.j   -0.81-0.59j  0.31+0.95j  0.31-0.95j -0.81+0.59j]
 [ 1.  +0.j   -0.81+0.59j  0.31-0.95j  0.31+0.95j -0.81-0.59j]
 [ 1.  +0.j    0.31+0.95j -0.81+0.59j -0.81-0.59j  0.31-0.95j]]


- Block Diagonal Matrix

In [9]:
from scipy.linalg import block_diag
A = [[1, 0],
     [0, 1]]
B = [[3, 4, 5],
     [6, 7, 8]]
C = [[7]]

block_diag(A, B, C)


array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 3, 4, 5, 0],
       [0, 0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0, 7]], dtype=int32)

In [12]:
P = np.zeros((2, 0), dtype='int32')
block_diag(A, P, B, C)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 3, 4, 5, 0],
       [0, 0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0, 7]], dtype=int32)

In [11]:
block_diag(1.0, [2, 3], [[4, 5], [6, 7]])

array([[1., 0., 0., 0., 0.],
       [0., 2., 3., 0., 0.],
       [0., 0., 0., 4., 5.],
       [0., 0., 0., 6., 7.]])

### References:
1. [Scipy Tutorials](https://docs.scipy.org/doc/scipy/reference/tutorial/index.html)